# === Vulnerability detection with ModernBERT + ONNX Runtime Training ===
task: vulnerability_detection

dummy_mode:
  enabled: true
  sample_size: 25          # quick smoke-test
  num_epochs: 1
  batch_size: 1
  max_length: 128

model:
  name: answerdotai/ModernBERT-base     # original repo (tokeniser + config)
  onnx_q4: onnx/model_q4.onnx           # path inside hub repo
  num_labels: 2

data:
  versions:
    default:
      max_length: 2048
      text_column: func_before
      label_column: vul
    dummy:
      max_length: 128
      text_column: func_before
      label_column: vul

training:
  versions:
    default:
      learning_rate:    5e-5
      num_epochs:       2
      batch_size:       4
      eval_batch_size:  4
      gradient_accumulation_steps: 8
      weight_decay:     0.01
      warmup_ratio:     0.1
      logging_steps:    50
      eval_strategy:    epoch
      save_strategy:    epoch
      save_total_limit: 2
      metric_for_best_model: f1
      gradient_checkpointing: false
      fp16: false
    dummy:
      learning_rate:    5e-5
      num_epochs:       1
      batch_size:       1
      eval_batch_size:  1
      gradient_accumulation_steps: 1
      weight_decay:     0.01
      warmup_ratio:     0.1
      logging_steps:    10
      eval_strategy:    "no"
      save_strategy:    "no"
      save_total_limit: 2
      metric_for_best_model: f1
      gradient_checkpointing: false
      fp16: false
