# Configuration for vulnerability detection task
task: vulnerability_detection

# Dummy mode configuration for testing
dummy_mode:
  enabled: true
  sample_size: 100
  num_epochs: 1
  batch_size: 4
  max_length: 128

model:
  name: bert-base-uncased
  type: sequence_classification
  precision: fp32
  device: auto
  num_labels: 2

# Data stage configurations
data:
  batch_size: 8
  shuffle: true
  num_workers: 2
  pin_memory: true
  max_length: 512
  truncation: true
  padding: max_length
  label_column: vulnerability
  text_column: code

# Training stage configurations
training:
  learning_rate: 2e-5
  num_epochs: 3
  optimizer: adamw
  scheduler: linear
  gradient_accumulation_steps: 4
  weight_decay: 0.01
  warmup_ratio: 0.1
  max_grad_norm: 1.0
  logging_steps: 100
  save_steps: 500
  eval_steps: 500
  evaluation_strategy: steps
  save_strategy: steps
  load_best_model_at_end: true
  metric_for_best_model: accuracy
  lr_scheduler_type: linear
  batch_size: 8
  eval_batch_size: 8
  gradient_checkpointing: true
  fp16: false
  bf16: false

# Inference stage configurations
inference:
  batch_size: 8
  num_workers: 2
  pin_memory: true
  max_length: 512
  return_tensors: pt
  return_attention_mask: true
  return_token_type_ids: true

# Energy monitoring configuration
energy:
  co2_conversion_factor: 0.233
  monitor_gpu: true
  monitor_cpu: true
  monitor_memory: true
  save_traces: true
  trace_interval: 1.0 